experiment_file:  'config_short_red-yellow.json'
preprocess:
  raw_data_dir: 'default'
  min_pass_freq: .1
  max_pass_freq: 10
  apply_referencing: 'average'
#  use decimate instead of downsample
  downsample_frequency: None
#  decimate_n:
  signal_duration_min: 0
  signal_duration_max: .65

process:
  n_folds:
  feature_selection:
  classifier:


