experiment_file:  'config_short_red-yellow.json'
preprocess:
  # this folder should be in data/raw
  session_dir: 'ses-ses-15-07-2022-short-rg'
  min_pass_freq: 1
  max_pass_freq: 20
  apply_referencing: 'average'
#  use decimate instead of downsample
  decim_factor: 2
#  decimate_n:
  signal_duration_min: .1
  signal_duration_max: .5

process:
  n_folds:
  feature_selection:
  classifier:


