experiment_file: 'config_short_red-yellow.json' #'config_long_blue-green.json' #  'config_short_red-yellow.json'
preprocess:
  # this folder should be in data/raw
  session_dir:  'ses-15-07-2022-short-rg'#'ses-lg'
#  'ses-15-07-2022-short-rg'
  min_pass_freq: 2
  max_pass_freq: 10
#  selected_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
  #[6, 7, 10, 5, 8, 11]
  apply_referencing: 'average'
#  use decimate instead of downsample
  decim_factor: 2


#  decimate_n:
  signal_duration_min: .1
  signal_duration_max: .6
#  return_full: 0

process:
  n_folds:
  feature_selection:
  classifier:

online:
  model_file: "test_model.pickle"
  ind_selected_channels: [6, 7, 10, 5, 8, 11]



